name: "Build Test Deploy"

on: 
  push:
   branches: [master, main]

env:
  PROJECT_VERSION: 1.0.0
  JAR_FILENAME: "helloworld-${{$PROJECT_VERSION}}.jar"
  MAVEN_OPTS: "-Dmaven.repo.local=/maven-cache/libs"
  
jobs:
  build-cache:
    runs-on: ubuntu-latest
    name: "Build and cache dependencies"
    steps:
      - name: "Set up JDK 17"
        uses: actions/setup-java@v4.5.0
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: maven

      - name: "Build project version ${{$PROJECT_VERSION}}"
        run: mvn clean package -DskipTests -Djar.finalName=$JAR_FILENAME

      - name: "Load cache"
        uses: actions/cache@v4.1.2
        with:
          path: "/maven-cache/libs"

      - name: "Upload a Build Artifact"
        uses: actions/upload-artifact@v4.4.3
        with: 
          name: Final_Jar
          path: $JAR_FILENAME
          
  tests:
    runs-on: ubuntu-latest
    name: "Run tests"
    needs: [build-cache]
    steps:
      - name: "Run tests"
        run: mvn test

  deploy:
    runs-on: ubuntu-latest
    name: "Deploy application"
    needs: [tests]
    steps:
      - name: "Download a Build Artifact"
        uses: actions/download-artifact@v4.1.8
        with:
         name: Final_Jar
    
